

BEGIN;

ALTER TABLE IF EXISTS users
  ADD COLUMN IF NOT EXISTS "partnerId" TEXT;

ALTER TABLE IF EXISTS users
  DROP CONSTRAINT IF EXISTS users_partnerid_fkey;

ALTER TABLE IF EXISTS users
  ADD CONSTRAINT users_partnerid_fkey
  FOREIGN KEY ("partnerId") REFERENCES partners(id)
  ON DELETE SET NULL
  ON UPDATE CASCADE;

CREATE INDEX IF NOT EXISTS idx_users_partnerId ON users("partnerId");

COMMIT;
